import React, { useState, useEffect, useRef } from "react";
import {
  Home, Radar as RadarIcon, MessageCircle, Video, Wallet, User,
  Coins, Gift, Heart, Lightbulb, Sparkles, LifeBuoy, MapPin,
  Crown, CheckCircle2, X, LogOut, Flame, Coffee, Flower2, Castle, ArrowLeft, Send,
} from "lucide-react";

type AppUser = {
  username: string; contact: string; password: string;
  daftar_tgl: string; isOwner?: boolean; subscribed?: boolean; coins?: number;
};

const FORBIDDEN = ["pemilik", "owner", "admin", "asisten"];
const OWNER_IDS = ["triangga_owner", "owner@localarea.id"];
const OWNER_PWDS = ["1106SoloRaya#Owner2024", "1106"];

function getDaysLeft(user: AppUser) {
  if (user.isOwner || user.subscribed) return 99;
  const daftar = new Date(user.daftar_tgl).getTime();
  const diffDays = Math.floor((Date.now() - daftar) / (1000*60*60*24));
  return 7 - diffDays;
}

export default function App() {
  const [authMode, setAuthMode] = useState<"daftar"|"masuk">("daftar");
  const [daftarForm, setDaftarForm] = useState({username:"",contact:"",password:"",confirm:""});
  const [masukForm, setMasukForm] = useState({identifier:"",password:""});
  const [daftarError, setDaftarError] = useState(""); const [masukError, setMasukError] = useState("");
  const [showOTP, setShowOTP] = useState(false); const [otpValues, setOtpValues] = useState(["","","",""]);
  const [otpError, setOtpError] = useState(""); const [toast, setToast] = useState("");
  const [loggedUser, setLoggedUser] = useState<AppUser|null>(null);
  const [mainTab, setMainTab] = useState<"beranda"|"radar"|"chat"|"live"|"dompet"|"profil">("beranda");
  const [chatDetail, setChatDetail] = useState<string|null>(null); const [chatInput, setChatInput] = useState("");
  const [gps, setGps] = useState<{lat:number|null;lng:number|null;accuracy:number|null;error:string|null;loading:boolean;timestamp:number|null;insideSolo:boolean}>({lat:null,lng:null,accuracy:null,error:null,loading:false,timestamp:null,insideSolo:false});

  useEffect(()=>{ const sess=localStorage.getItem("la_session"); if(sess){ try{setLoggedUser(JSON.parse(sess))}catch{} } },[]);
  useEffect(()=>{ if(toast){ const t=setTimeout(()=>setToast(""),3000); return()=>clearTimeout(t);} },[toast]);

  const SOLO_CENTER={lat:-7.5713,lng:110.8227};
  const haversineKm=(lat1:number,lng1:number,lat2:number,lng2:number)=>{ const R=6371; const dLat=((lat2-lat1)*Math.PI)/180; const dLng=((lng2-lng1)*Math.PI)/180; const a=Math.sin(dLat/2)**2+Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLng/2)**2; return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a)); };
  const isInsideSoloRaya=(lat:number,lng:number)=>{ const dist=haversineKm(lat,lng,SOLO_CENTER.lat,SOLO_CENTER.lng); const inBbox=lat>=-8.2&&lat<=-7.0&&lng>=110.3&&lng<=111.5; return dist<=35||inBbox; };
  const requestGps=()=>{ if(!navigator.geolocation){ setGps(p=>({...p,error:"GPS ora didukung",loading:false})); return;} setGps(p=>({...p,loading:true,error:null})); navigator.geolocation.getCurrentPosition((pos)=>{ setGps({lat:pos.coords.latitude,lng:pos.coords.longitude,accuracy:pos.coords.accuracy,error:null,loading:false,timestamp:pos.timestamp,insideSolo:isInsideSoloRaya(pos.coords.latitude,pos.coords.longitude)}) },(err)=>{ let msg="Gagal GPS"; if(err.code===1)msg="Izin GPS ditolak"; setGps(p=>({...p,error:msg,loading:false})) },{enableHighAccuracy:true,timeout:15000,maximumAge:0}) };
  useEffect(()=>{ if(mainTab==="radar") requestGps(); },[mainTab]);

  const handleDaftar=()=>{
    setDaftarError(""); const u=daftarForm.username.toLowerCase();
    if(FORBIDDEN.some(f=>u.includes(f))){ setDaftarError("Username ora oleh nggo kata pemilik/owner/admin"); return; }
    if(!daftarForm.username||!daftarForm.contact||!daftarForm.password){ setDaftarError("Isi kabeh form"); return; }
    if(daftarForm.password!==daftarForm.confirm){ setDaftarError("Password ora podo"); return; }
    setShowOTP(true);
  };
  const verifyOTP=()=>{ if(otpValues.join("")!=="1234"){ setOtpError("Kode salah, coba 1234"); return;} const users:AppUser[]=JSON.parse(localStorage.getItem("la_users")||"[]"); const newUser:AppUser={username:daftarForm.username,contact:daftarForm.contact,password:daftarForm.password,daftar_tgl:new Date().toISOString(),coins:0}; users.push(newUser); localStorage.setItem("la_users",JSON.stringify(users)); setShowOTP(false); setToast("Daftar sukses, silakan Masuk"); setAuthMode("masuk"); setOtpValues(["","","",""]); };
  const handleMasuk=()=>{
    setMasukError(""); const id=masukForm.identifier; const pw=masukForm.password;
    if(OWNER_IDS.includes(id)&&OWNER_PWDS.includes(pw)){ const owner:AppUser={username:"triangga_owner",contact:"owner@localarea.id",password:pw,daftar_tgl:new Date().toISOString(),isOwner:true,coins:9999}; setLoggedUser(owner); localStorage.setItem("la_session",JSON.stringify(owner)); return; }
    const users:AppUser[]=JSON.parse(localStorage.getItem("la_users")||"[]"); const found=users.find(u=>u.username===id||u.contact===id); if(!found){ setMasukError("Akun belum daftar"); return;} if(found.password!==pw){ setMasukError("Password salah"); return;} setLoggedUser(found); localStorage.setItem("la_session",JSON.stringify(found));
  };
  const handleLogout=()=>{ localStorage.removeItem("la_session"); setLoggedUser(null); setMainTab("beranda"); };
  if(!loggedUser){
    return(
      <div className="min-h-screen bg-[#0a0a0a] text-white flex items-center justify-center p-4 font-sans">
        <div className="w-full max-w-[380px] bg-[#111] border border-[#222] rounded-[24px] p-6">
          <h1 className="text-[22px] font-black tracking-widest text-[#FFD60A] text-center">LOCAL AREA</h1><p className="text-[10px] text-[#666] text-center tracking-widest mb-6">SOLO RAYA • Radar • Chat • Live • Dompet</p>
          <div className="flex bg-[#0a0a0a] rounded-full p-1 mb-6 border border-[#222]"><button onClick={()=>setAuthMode("daftar")} className={`flex-1 py-2.5 rounded-full text-[12px] font-black tracking-wide ${authMode==="daftar"?"bg-[#FFD60A] text-black":"text-[#666]"}`}>DAFTAR</button><button onClick={()=>setAuthMode("masuk")} className={`flex-1 py-2.5 rounded-full text-[12px] font-black tracking-wide ${authMode==="masuk"?"bg-[#FFD60A] text-black":"text-[#666]"}`}>MASUK</button></div>
          {authMode==="daftar"?(
            <div className="space-y-3"><input value={daftarForm.username} onChange={e=>setDaftarForm({...daftarForm,username:e.target.value})} placeholder="Username anonim" className="w-full bg-[#0a0a0a] border border-[#222] rounded-xl px-4 py-3 text-[13px] outline-none focus:border-[#FFD60A]"/><input value={daftarForm.contact} onChange={e=>setDaftarForm({...daftarForm,contact:e.target.value})} placeholder="Email atau No WA (contoh: email@gmail.com / 08xxxx)" className="w-full bg-[#0a0a0a] border border-[#222] rounded-xl px-4 py-3 text-[13px] outline-none focus:border-[#FFD60A]"/><p className="text-[10px] text-[#555] px-1">ISO nganggo email opo no wa konfirmasine</p><input type="password" value={daftarForm.password} onChange={e=>setDaftarForm({...daftarForm,password:e.target.value})} placeholder="Password" className="w-full bg-[#0a0a0a] border border-[#222] rounded-xl px-4 py-3 text-[13px] outline-none focus:border-[#FFD60A]"/><input type="password" value={daftarForm.confirm} onChange={e=>setDaftarForm({...daftarForm,confirm:e.target.value})} placeholder="Konfirmasi Password" className="w-full bg-[#0a0a0a] border border-[#222] rounded-xl px-4 py-3 text-[13px] outline-none focus:border-[#FFD60A]"/>{daftarError&&<p className="text-[11px] text-red-400 bg-red-500/10 border border-red-500/20 rounded-lg p-2">{daftarError}</p>}<button onClick={handleDaftar} className="w-full bg-[#FFD60A] text-black font-black text-[13px] tracking-widest py-3.5 rounded-xl mt-2">DAFTAR SEKARANG</button></div>
          ):(
            <div className="space-y-3"><input value={masukForm.identifier} onChange={e=>setMasukForm({...masukForm,identifier:e.target.value})} placeholder="Username / Email / No WA" className="w-full bg-[#0a0a0a] border border-[#222] rounded-xl px-4 py-3 text-[13px] outline-none focus:border-[#FFD60A]"/><input type="password" value={masukForm.password} onChange={e=>setMasukForm({...masukForm,password:e.target.value})} placeholder="Password" className="w-full bg-[#0a0a0a] border border-[#222] rounded-xl px-4 py-3 text-[13px] outline-none focus:border-[#FFD60A]"/>{masukError&&<p className="text-[11px] text-red-400 bg-red-500/10 border border-red-500/20 rounded-lg p-2">{masukError}</p>}<button onClick={handleMasuk} className="w-full bg-[#FFD60A] text-black font-black text-[13px] tracking-widest py-3.5 rounded-xl">MASUK</button><p className="text-[10px] text-[#444] text-center">Owner: triangga_owner / 1106 (rahasia)</p></div>
          )}
          {showOTP&&<div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4"><div className="bg-[#151515] border border-[#222] rounded-[20px] p-6 w-full max-w-[320px] text-center"><h3 className="font-black text-[14px]">KONFIRMASI OTP</h3><p className="text-[11px] text-[#888] mt-1">Kode dikirim ke {daftarForm.contact} (simulasi: 1234)</p><div className="flex gap-2 justify-center mt-4">{otpValues.map((v,i)=><input key={i} value={v} onChange={e=>{ const nv=[...otpValues]; nv[i]=e.target.value.slice(-1); setOtpValues(nv); }} className="w-12 h-12 bg-[#0a0a0a] border border-[#222] rounded-xl text-center font-black text-[16px] outline-none focus:border-[#FFD60A]" />)}</div>{otpError&&<p className="text-[10px] text-red-400 mt-2">{otpError}</p>}<button onClick={verifyOTP} className="w-full bg-[#FFD60A] text-black font-black text-[12px] py-3 rounded-xl mt-4">VERIFIKASI</button><button onClick={()=>setShowOTP(false)} className="w-full text-[11px] text-[#666] mt-2">Batal</button></div></div>}
          {toast&&<div className="fixed bottom-6 left-1/2 -translate-x-1/2 bg-[#FFD60A] text-black text-[12px] font-bold px-5 py-3 rounded-full z-[100]">{toast}</div>}
        </div>
      </div>
    )
  }
  const daysLeft=getDaysLeft(loggedUser); const isLocked=!loggedUser.isOwner&&!loggedUser.subscribed&&daysLeft<=0;
  return(
    <div className="min-h-screen bg-[#0a0a0a] text-white flex justify-center font-sans"><div className="w-full max-w-[420px] bg-[#0a0a0a] min-h-screen relative pb-[80px] border-x border-[#111]">
      <div className="sticky top-0 bg-[#0a0a0a]/95 backdrop-blur-xl border-b border-[#111] px-4 py-3 flex justify-between items-center z-20"><div className="flex items-center gap-2"><div className="w-9 h-9 bg-[#FFD60A] rounded-full flex items-center justify-center text-black font-black text-[14px]">LA</div><div><p className="font-black text-[14px] tracking-widest">LOCAL AREA</p><p className="text-[10px] text-[#666]">SOLO RAYA</p></div></div><div className="flex items-center gap-2"><div className="bg-[#111] border border-[#222] rounded-full px-3 py-1.5 flex items-center gap-1"><Coins size={12} className="text-[#FFD60A]"/><span className="text-[12px] font-bold">{loggedUser.isOwner?9999:loggedUser.coins}</span></div>{loggedUser.isOwner&&<span className="bg-[#FFD60A] text-black text-[10px] font-black px-2.5 py-1 rounded-full flex items-center gap-1"><Crown size={12}/>OWNER</span>}</div></div>
      <div className="p-4">
        {mainTab==="beranda"&&<div className="space-y-4"><div className="bg-gradient-to-br from-[#FFD60A]/20 to-[#ffae00]/10 border border-[#FFD60A]/20 rounded-[20px] p-4"><p className="text-[11px] text-[#FFD60A] font-bold">TRIAL GRATIS</p><p className="text-[16px] font-black mt-1">{loggedUser.isOwner?"Unlimited Owner":`Sisa ${Math.max(0,daysLeft)} hari trial`}</p><p className="text-[11px] text-[#888] mt-1">Gift kudu topup, lewat 7 dino topup 10RB / 1 bulan</p></div><div className="grid grid-cols-2 gap-3"><button className="bg-[#151515] border border-[#222] rounded-2xl p-4 text-left"><Sparkles size={18} className="text-[#FFD60A]"/><p className="text-[12px] font-bold mt-2">Saran</p></button><button className="bg-[#151515] border border-[#222] rounded-2xl p-4 text-left"><Gift size={18} className="text-[#FFD60A]"/><p className="text-[12px] font-bold mt-2">Gift sesuai isi</p></button></div><button onClick={()=>setMainTab("radar")} className="w-full bg-[#FFD60A] text-black font-black py-3.5 rounded-xl text-[12px] tracking-widest">BUKA RADAR MAKSIMAL</button><button className="w-full bg-[#111] border border-[#222] rounded-xl py-3 flex items-center justify-center gap-2 text-[12px]"><LifeBuoy size={14}/> pertolongan</button></div>}
        {mainTab==="radar"&&<div className="space-y-3"><h2 className="font-black tracking-widest text-[14px]">RADAR • RADIUS MAKSIMAL</h2><p className="text-[11px] text-[#666]">GPS Real • Tanpa batas jarak • Sak Solo Raya (35km) • ORA ngawur</p><div className="bg-[#111] border border-[#222] rounded-2xl p-4">{gps.loading&&<p className="text-[12px] text-[#FFD60A]">Ndeteksi GPS...</p>}{gps.error&&<div><p className="text-[11px] text-red-400">{gps.error}</p><button onClick={requestGps} className="mt-2 bg-[#222] text-[11px] px-3 py-1.5 rounded-full">Coba Lagi</button></div>}{gps.lat&&<div className="space-y-2"><div className="flex items-center gap-2"><MapPin size={14} className="text-[#FFD60A]"/><p className="text-[11px] font-bold">{gps.lat.toFixed(5)}, {gps.lng?.toFixed(5)} • {gps.accuracy?.toFixed(0)}m akurat</p></div><p className="text-[10px] text-[#666]">GPS Aktif - Sesuai lokasi asli HP mu</p><div className={`text-[10px] px-2.5 py-1 rounded-full inline-flex ${gps.insideSolo?"bg-green-500/20 text-green-400":"bg-[#222] text-[#888]"}`}>{gps.insideSolo?"✓ Di Solo Raya - Radius maksimal aktif":"Di luar Solo Raya"}</div></div>}</div><div className="bg-[#151515] border border-[#FFD60A]/30 rounded-[20px] p-4 flex gap-3"><div className="w-12 h-12 rounded-full bg-[#FFD60A] flex items-center justify-center text-black font-black">AS</div><div className="flex-1"><p className="text-[13px] font-bold flex items-center gap-2">Asisten • LOCAL AREA <span className="bg-green-500 w-2 h-2 rounded-full inline-block"></span></p><p className="text-[11px] text-[#888] mt-1">Online - Siap mandu carane nggo apk & hasilne duet (Gift jadi saldo WD). Radar maksimal 35km, ORA ngawur, ORA demo.</p><button onClick={()=>setMainTab("chat")} className="mt-2 bg-[#FFD60A] text-black text-[10px] font-black px-3 py-1.5 rounded-full">CHAT ASISTEN</button></div></div><div className="bg-[#0f0f0f] border border-[#1a1a1a] rounded-2xl p-4 text-center"><p className="text-[11px] text-[#666]">Belum ada wong sekitar - Radius maksimal Solo Raya aktif</p><p className="text-[10px] text-[#444] mt-1">Ajak konco mu daftar, bakal muncul neng radar otomatis sesuai GPS real</p></div><p className="text-[10px] text-[#333] text-center">Radar GPS Real - Jangkauan maksimal Solo Raya - Update tiap 30 detik</p></div>}
        {mainTab==="chat"&&!chatDetail&&<div className="space-y-2"><h2 className="font-black tracking-widest text-[14px] p-1">CHAT</h2><div onClick={()=>setChatDetail("asisten")} className="bg-[#151515] border border-[#FFD60A]/30 rounded-2xl p-3 flex gap-3 cursor-pointer"><div className="w-10 h-10 bg-[#FFD60A] rounded-full flex items-center justify-center text-black font-black text-[12px]">AS</div><div className="flex-1"><p className="text-[12px] font-bold">Asisten Lokal</p><p className="text-[11px] text-[#888] truncate">Halo {loggedUser.username}! Aku siap mandu kowe...</p></div><div className="bg-green-500 w-2 h-2 rounded-full mt-2"></div></div><p className="text-[10px] text-[#444] text-center mt-4">Demo Sinta, Bima, Rara wes tak guak kabeh - mung Asisten tok</p></div>}
        {mainTab==="chat"&&chatDetail==="asisten"&&<div className="flex flex-col h-[calc(100vh-140px)]"><div className="flex items-center gap-2 border-b border-[#111] pb-3"><button onClick={()=>setChatDetail(null)} className="p-2 bg-[#111] rounded-full"><ArrowLeft size={16}/></button><p className="font-bold text-[13px]">Asisten Lokal</p></div><div className="flex-1 overflow-y-auto py-4 space-y-3"><div className="bg-[#151515] border border-[#222] rounded-2xl rounded-tl-sm p-3 max-w-[85%]"><p className="text-[12px] leading-relaxed">Halo {loggedUser.username}! 👋 Aku Asisten LOCAL AREA. Radar ku wes maksimal 35km sak Solo Raya, GPS real ora ngawur. Trial 7 dino gratis, tapi nek arep nge-gift kudu Topup. Gift rego sesuai isine, dadi saldo iso WD DANA/ShopeePay tiap Senin & Kamis. Ojo lali ajak konco mu daftar ben radar mu rame! 🔥</p></div></div><div className="flex gap-2 pt-2"><input value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder="Tulis pesan..." className="flex-1 bg-[#111] border border-[#222] rounded-full px-4 py-2.5 text-[12px] outline-none"/><button className="bg-[#FFD60A] text-black w-10 h-10 rounded-full flex items-center justify-center"><Send size={16}/></button></div></div>}
        {mainTab==="dompet"&&<div className="space-y-4"><h2 className="font-black tracking-widest text-[14px]">DOMPET</h2><div className="bg-[#111] border border-[#222] rounded-2xl p-4"><p className="text-[11px] text-[#666]">Saldo</p><p className="text-[22px] font-black flex items-center gap-2"><Coins className="text-[#FFD60A]"/>{loggedUser.isOwner?9999:loggedUser.coins} Coin</p><p className="text-[10px] text-[#555] mt-1">{loggedUser.isOwner?"Owner unlimited":`Trial sisa ${Math.max(0,daysLeft)} hari`}</p></div>{!loggedUser.isOwner&&!loggedUser.subscribed&&<button onClick={()=>{ const u={...loggedUser,subscribed:true}; setLoggedUser(u); localStorage.setItem("la_session",JSON.stringify(u)); setToast("Topup 10RB sukses - aktif 1 bulan"); }} className="w-full bg-[#FFD60A] text-black font-black py-3.5 rounded-xl text-[12px] tracking-widest">TOPUP 10RB / 1 BULAN</button>}<div className="bg-[#151515] border border-[#222] rounded-2xl p-3 grid grid-cols-2 gap-2 text-[11px]"><div className="bg-[#0a0a0a] rounded-xl p-3 flex justify-between"><span className="flex items-center gap-1"><Flower2 size={12}/>Mawar</span><span className="font-bold">1k</span></div><div className="bg-[#0a0a0a] rounded-xl p-3 flex justify-between"><span className="flex items-center gap-1"><Coffee size={12}/>Kopi</span><span className="font-bold">5k</span></div><div className="bg-[#0a0a0a] rounded-xl p-3 flex justify-between"><span>Nasi Liwet</span><span className="font-bold">20k</span></div><div className="bg-[#0a0a0a] rounded-xl p-3 flex justify-between"><span className="flex items-center gap-1"><Castle size={12}/>Keraton</span><span className="font-bold">250k</span></div></div></div>}
        {mainTab==="profil"&&<div className="space-y-4"><h2 className="font-black tracking-widest text-[14px]">PROFIL</h2><div className="bg-[#151515] border border-[#222] rounded-[20px] p-5 flex flex-col items-center"><div className="w-16 h-16 rounded-full bg-[#FFD60A] flex items-center justify-center text-black font-black text-[20px]">{loggedUser.username.slice(0,2).toUpperCase()}</div><p className="font-black mt-3 flex items-center gap-2">{loggedUser.username}{loggedUser.isOwner&&<span className="bg-[#FFD60A] text-black text-[9px] px-2 py-0.5 rounded-full">OWNER</span>}</p><p className="text-[11px] text-[#666]">{loggedUser.contact}</p></div><button onClick={handleLogout} className="w-full bg-[#1a1a1a] border border-[#222] text-[#888] font-bold text-[12px] py-3 rounded-xl flex items-center justify-center gap-2"><LogOut size={16}/>Keluar</button></div>}
      </div>
      <div className="absolute bottom-0 left-0 right-0 bg-[#111]/95 backdrop-blur-xl border-t border-[#1e1e1e] flex justify-around py-2.5 z-30">{[{id:"beranda",icon:Home,label:"Beranda"},{id:"radar",icon:RadarIcon,label:"Radar"},{id:"chat",icon:MessageCircle,label:"Chat"},{id:"live",icon:Video,label:"Live"},{id:"dompet",icon:Wallet,label:"Dompet"},{id:"profil",icon:User,label:"Profil"}].map(t=><button key={t.id} onClick={()=>setMainTab(t.id as any)} className={`flex flex-col items-center gap-1 min-w-[48px] ${mainTab===t.id?"text-[#FFD60A]":"text-[#555]"}`}><t.icon size={20}/><span className="text-[9px] font-bold">{t.label}</span></button>)}</div>
      {isLocked&&mainTab!=="dompet"&&<div className="absolute inset-0 bg-[#0a0a0a]/95 backdrop-blur-md z-40 flex flex-col items-center justify-center p-8 text-center"><Flame size={28} className="text-[#FFD60A] mb-3"/><h3 className="font-black">TRIAL HABIS</h3><p className="text-[12px] text-[#888] mt-2">Topup 10RB buat lanjut 1 bulan</p><button onClick={()=>setMainTab("dompet")} className="mt-4 bg-[#FFD60A] text-black font-black text-[12px] px-6 py-3 rounded-xl">TOPUP 10RB</button></div>}
      {toast&&<div className="fixed bottom-[90px] left-1/2 -translate-x-1/2 bg-[#FFD60A] text-black text-[12px] font-bold px-5 py-3 rounded-full z-[100]">{toast}</div>}
    </div></div>
  )
}
