import React, { useState, useRef } from 'react';
const LANGUAGES = { id: { name: 'Indonesia', flag: '🇮🇩' }, en: { name: 'English', flag: '🇬🇧' }, zh: { name: '中文', flag: '🇨🇳' }, hk: { name: '廣東話', flag: '🇭🇰' }, ms: { name: 'Melayu', flag: '🇲🇾' }, jp: { name: '日本語', flag: '🇯🇵' }, kr: { name: '한국어', flag: '🇰🇷' } };
const T = {
  id: { loginTitle: 'MAHA REAL', loginSub: 'Cari Teman, Hiburan & Cuan', name: 'Nama', emailWa: 'Email / WA', pass: 'Password', daftar: 'Daftar Sekarang', verifTitle: 'Pilih Verifikasi (C)', verifEmail: 'Verifikasi Email OTP', verifWa: 'Verifikasi WA OTP', otpSent: 'OTP terkirim ke', otp: 'Kode OTP', verifBtn: 'Verifikasi & Masuk', radar: 'Radar', chat: 'Chat', hiburan: 'Hiburan', dompet: 'Dompet', profil: 'Profil', online: 'ONLINE', offline: 'OFFLINE', baruOnline: 'Baru Online', chatAntiIlang: 'Chat Anti-Hilang', ketikPesan: 'Ketik pesan...', kirim: 'Kirim', drakor: 'Drama Korea', game: 'Game Cuan', karaoke: 'Karaoke', live: 'Live', nonton: 'Nonton', saldo: 'Saldo', coins: 'Coins', topup: 'Topup REAL', wd: 'Tarik (WD)', riwayat: 'Riwayat Transaksi', kotakSaran: 'Kotak Saran', saran: 'Saran', bug: 'Bug', laporUser: 'Lapor User', tulisSaran: 'Tulis saran...', kirimSaran: 'Kirim', dibalas: 'Dibalas Pemilik', tombolSos: 'TOMBOL SOS', sosDesc: 'Butuh pertolongan? Tekan untuk konek 5 orang terdekat ONLINE', sosActive: 'Mengirim SOS...', lonceng: 'Notifikasi', dataTerenkripsi: 'Terenkripsi & Aman (Hanya Pemilik)', bahasa: 'Ganti Bahasa', keluar: 'Keluar', selamat: 'Selamat Datang', playerTitle: 'Player Drakor', gift: 'Gift', like: 'Like' },
  en: { loginTitle: 'MAHA REAL', loginSub: 'Find Friends, Fun & Money', name: 'Name', emailWa: 'Email / WA', pass: 'Password', daftar: 'Register', verifTitle: 'Choose Verification (C)', verifEmail: 'Email OTP', verifWa: 'WA OTP', otpSent: 'OTP sent to', otp: 'OTP Code', verifBtn: 'Verify & Enter', radar: 'Radar', chat: 'Chat', hiburan: 'Entertainment', dompet: 'Wallet', profil: 'Profile', online: 'ONLINE', offline: 'OFFLINE', baruOnline: 'New Online', chatAntiIlang: 'Anti-Lost Chat', ketikPesan: 'Type...', kirim: 'Send', drakor: 'K-Drama', game: 'Game', karaoke: 'Karaoke', live: 'Live', nonton: 'Watch', saldo: 'Balance', coins: 'Coins', topup: 'Topup REAL', wd: 'Withdraw', riwayat: 'History', kotakSaran: 'Suggestion Box', saran: 'Feature', bug: 'Bug', laporUser: 'Report', tulisSaran: 'Write...', kirimSaran: 'Send', dibalas: 'Replied by Owner', tombolSos: 'SOS BUTTON', sosDesc: 'Need help? Connect 5 nearest ONLINE', sosActive: 'Sending SOS...', lonceng: 'Notifications', dataTerenkripsi: 'Encrypted (Owner Only)', bahasa: 'Language', keluar: 'Logout', selamat: 'Welcome', playerTitle: 'K-Drama Player', gift: 'Gift', like: 'Like' }
};
const getT = (lang) => T[lang] || T.id;
const radarUsers = [
  { id: 1, name: 'Sinta - Solo', distance: '0.8 km', status: 'online', avatar: 'https://i.pravatar.cc/150?img=5' },
  { id: 2, name: 'Rina - Jogja', distance: '1.2 km', status: 'online', avatar: 'https://i.pravatar.cc/150?img=9' },
  { id: 3, name: 'Dewi - Semarang', distance: '2.5 km', status: 'offline', avatar: 'https://i.pravatar.cc/150?img=32' },
  { id: 4, name: 'Budi - Solo', distance: '0.5 km', status: 'online', avatar: 'https://i.pravatar.cc/150?img=15' },
  { id: 5, name: 'Mei Ling - HK', distance: '1.1 km', status: 'online', avatar: 'https://i.pravatar.cc/150?img=29' },
];
const drakorList = [
  { id: 1, title: 'My Love From The Star', eps: 'Eps 1', thumb: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=300', video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', desc: 'Romantis - Sub Indo' },
  { id: 2, title: 'Goblin', eps: 'Eps 1', thumb: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=300', video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4', desc: 'Fantasy Romance' },
  { id: 3, title: 'Crash Landing On You', eps: 'Eps 1', thumb: 'https://images.unsplash.com/photo-1515634928627-2a4e0dae3ddf?w=300', video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', desc: 'CLOY Sub Indo' },
];
export default function App() {
  const [lang, setLang] = useState('id'); const t = getT(lang);
  const [isLoggedIn, setIsLoggedIn] = useState(false); const [isOwner, setIsOwner] = useState(false);
  const [authStep, setAuthStep] = useState('login'); const [verifMethod, setVerifMethod] = useState(null);
  const [form, setForm] = useState({ name: '', email: '', pass: '' }); const [otp, setOtp] = useState('');
  const [activeTab, setActiveTab] = useState('radar');
  const [chatMsgs, setChatMsgs] = useState([{ from: 'other', text: 'Hai radar mu ketok ora?' }, { from: 'me', text: 'Ketok ijo kedip!' }]);
  const [chatInput, setChatInput] = useState(''); const chatEndRef = useRef(null);
  const [notifCount, setNotifCount] = useState(3); const [showNotif, setShowNotif] = useState(false);
  const [sosActive, setSosActive] = useState(false); const [playingVideo, setPlayingVideo] = useState(null);
  const [balance, setBalance] = useState(150000); const [coins, setCoins] = useState(5400);
  const [transactions, setTransactions] = useState([{ type: 'Topup REAL', amount: '+ Rp 100.000', status: 'Berhasil', time: 'Hari ini' }]);
  const [saranList, setSaranList] = useState([{ text: 'Tambah filter umur', reply: 'Siap ditambah' }]); const [saranText, setSaranText] = useState('');
  const handleLogin = () => { if (form.name === 'pemilik' && form.pass === '1106') { setIsOwner(true); setIsLoggedIn(true); return; } if (form.name && form.email && form.pass) setAuthStep('verifChoice'); else alert('Isi Nama, Email/WA, Password'); };
  const handleSendChat = () => { if (!chatInput) return; setChatMsgs(prev => [...prev, { from: 'me', text: chatInput }]); setChatInput(''); setTimeout(() => setChatMsgs(prev => [...prev, { from: 'other', text: 'Oke siap! ❤️' }]), 800); };
  const handleTopup = () => { setBalance(b => b + 100000); setTransactions(prev => [{ type: 'Topup REAL Midtrans Production', amount: '+ Rp 100.000', status: 'Berhasil', time: 'Baru saja' }, ...prev]); alert('Topup REAL Berhasil! Server Key Terenkripsi'); };
  const handleSos = () => { setSosActive(true); setTimeout(() => { setSosActive(false); alert('SOS TERKIRIM! 5 orang terdekat ONLINE dapat chat darurat.'); }, 2000); };
  if (!isLoggedIn) {
    return (
      <div className="min-h-screen bg-black text-white flex items-center justify-center p-4">
        <div className="w-full max-w-md bg-[#1a1a1a] rounded-[32px] p-8 border border-white/10">
          <h1 className="text-3xl font-black bg-gradient-to-r from-pink-500 to-violet-500 bg-clip-text text-transparent">{t.loginTitle}</h1>
          <p className="text-white/60 mb-6">{t.loginSub}</p>
          {authStep === 'login' && (<><input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder={t.name} className="w-full bg-black border border-white/10 rounded-2xl p-4 mb-3" /><input value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="Email / WA" className="w-full bg-black border border-white/10 rounded-2xl p-4 mb-3" /><input type="password" value={form.pass} onChange={e => setForm({ ...form, pass: e.target.value })} placeholder="Password (pemilik/1106)" className="w-full bg-black border border-white/10 rounded-2xl p-4 mb-6" /><button onClick={handleLogin} className="w-full bg-gradient-to-r from-pink-500 to-violet-500 rounded-2xl p-4 font-bold">Daftar / Masuk</button></>)}
          {authStep === 'verifChoice' && (<div><h2 className="font-bold text-xl mb-4">{t.verifTitle}</h2><button onClick={() => { setVerifMethod('email'); setAuthStep('otp'); }} className="w-full bg-white text-black rounded-2xl p-4 mb-3 font-bold">📧 {t.verifEmail}</button><button onClick={() => { setVerifMethod('wa'); setAuthStep('otp'); }} className="w-full bg-green-500 rounded-2xl p-4 font-bold">💬 {t.verifWa}</button></div>)}
          {authStep === 'otp' && (<div><p className="mb-4">{t.otpSent} {form.email}</p><input value={otp} onChange={e => setOtp(e.target.value)} placeholder="123456" className="w-full bg-black border border-white/10 rounded-2xl p-4 text-center text-2xl tracking-widest" /><button onClick={() => otp.length >= 4 && setIsLoggedIn(true)} className="w-full mt-4 bg-gradient-to-r from-pink-500 to-violet-500 rounded-2xl p-4 font-bold">{t.verifBtn}</button></div>)}
        </div>
      </div>
    );
  }
  return (
    <div className="min-h-screen bg-black text-white max-w-[480px] mx-auto border-x border-white/5 flex flex-col relative">
      <div className="sticky top-0 z-20 bg-black/80 backdrop-blur-xl border-b border-white/10 p-4 flex justify-between items-center">
        <h1 className="font-black bg-gradient-to-r from-pink-500 to-violet-500 bg-clip-text text-transparent">MAHA REAL {isOwner && '👑'}</h1>
        <div className="flex gap-2"><button onClick={() => setShowNotif(!showNotif)} className="relative bg-[#1a1a1a] w-10 h-10 rounded-full">🔔{notifCount > 0 && <span className="absolute -top-1 -right-1 bg-red-500 text-xs w-5 h-5 rounded-full flex items-center justify-center">{notifCount}</span>}</button><select value={lang} onChange={e => setLang(e.target.value)} className="bg-[#1a1a1a] rounded-full px-2 text-xs border border-white/10"><option value="id">🇮🇩</option><option value="en">🇬🇧</option><option value="zh">🇨🇳</option><option value="hk">🇭🇰</option><option value="ms">🇲🇾</option><option value="jp">🇯🇵</option><option value="kr">🇰🇷</option></select></div>
      </div>
      {showNotif && (<div className="absolute top-[64px] right-4 z-30 bg-[#1a1a1a] border border-white/10 rounded-2xl p-4 w-72"><h3 className="font-bold mb-2">{t.lonceng}</h3><div className="text-sm space-y-2"><div className="bg-black p-2 rounded-xl">🎁 Gift 100 Coins</div><div className="bg-black p-2 rounded-xl">💬 {t.dibalas}</div><div className="bg-red-500/20 p-2 rounded-xl">🚨 SOS 0.8km</div></div></div>)}
      <div className="flex-1 overflow-auto pb-24">
        {activeTab === 'radar' && (<div className="p-4"><div className="bg-gradient-to-br from-red-600 to-red-800 rounded-[24px] p-4 mb-6"><h3 className="font-black">🚨 {t.tombolSos}</h3><p className="text-xs mb-3">{t.sosDesc}</p><button onClick={handleSos} className="w-full bg-white text-red-600 font-black rounded-2xl py-3">{sosActive ? t.sosActive : 'TEKAN SOS'}</button></div><h2 className="font-bold mb-3">● {t.baruOnline} ONLINE</h2><div className="grid grid-cols-2 gap-3">{radarUsers.map(u => (<div key={u.id} className="bg-[#1a1a1a] rounded-[24px] p-3 border border-white/5 relative">{u.status === 'online' && <><div className="absolute top-3 right-3 w-3 h-3 bg-green-400 rounded-full animate-ping"></div><div className="absolute top-3 right-3 w-3 h-3 bg-green-400 rounded-full"></div></>}<img src={u.avatar} className="w-16 h-16 rounded-full mx-auto mb-2" /><h3 className="font-bold text-sm text-center">{u.name}</h3><p className="text-xs text-center text-white/50">{u.distance}</p><p className={`text-[10px] text-center font-bold ${u.status === 'online' ? 'text-green-400' : 'text-white/30'}`}>● {u.status === 'online' ? t.online : t.offline}</p><button onClick={() => setActiveTab('chat')} className="w-full mt-2 bg-white/10 rounded-full py-1 text-xs">Chat</button></div>))}</div></div>)}
        {activeTab === 'chat' && (<div className="p-4 flex flex-col h-[70vh]"><div className="bg-[#1a1a1a] rounded-xl p-2 mb-3 text-xs text-green-400">● {t.chatAntiIlang}</div><div className="flex-1 overflow-auto space-y-3 bg-black/50 rounded-2xl p-3">{chatMsgs.map((m, i) => <div key={i} className={`max-w-[80%] p-3 rounded-2xl text-sm ${m.from === 'me' ? 'bg-gradient-to-r from-pink-500 to-violet-500 ml-auto' : 'bg-[#1a1a1a]'}`}>{m.text}</div>)}<div ref={chatEndRef} /></div><div className="flex gap-2 mt-3"><input value={chatInput} onChange={e => setChatInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && handleSendChat()} placeholder={t.ketikPesan} className="flex-1 bg-[#1a1a1a] border border-white/10 rounded-full px-4 py-3 text-sm" /><button onClick={handleSendChat} className="bg-white text-black rounded-full px-6 font-bold">{t.kirim}</button></div></div>)}
        {activeTab === 'hiburan' && (<div className="p-4 space-y-6"><div><h2 className="font-black text-lg mb-3">🎬 {t.drakor} - REAL PLAYER</h2><div className="space-y-3">{drakorList.map(v => (<div key={v.id} className="bg-[#1a1a1a] rounded-2xl overflow-hidden border border-white/5"><img src={v.thumb} className="w-full h-32 object-cover" /><div className="p-3"><h3 className="font-bold text-sm">{v.title} - {v.eps}</h3><p className="text-xs text-white/50">{v.desc}</p><div className="flex gap-2 mt-2"><button onClick={() => setPlayingVideo(v)} className="flex-1 bg-gradient-to-r from-pink-500 to-violet-500 rounded-full py-2 text-xs font-bold">▶️ {t.nonton} + Player</button><button className="bg-white/10 rounded-full px-3 py-2 text-xs">🎁</button></div></div></div>))}</div></div><div><h2 className="font-black text-lg mb-3">🎮 Game + 🎤 Karaoke + Live</h2><div className="bg-[#1a1a1a] rounded-2xl p-4 flex justify-between mb-2"><p className="text-sm">🎮 Ludo Cuan - Menang 500 Coins</p><button className="bg-green-500 text-black rounded-full px-3 py-1 text-xs">Main</button></div><div className="bg-[#1a1a1a] rounded-2xl p-4 flex justify-between mb-2"><p className="text-sm">🎤 Rungkad - Happy Asmara</p><button className="bg-pink-500 rounded-full px-3 py-1 text-xs">Nyanyi</button></div><div className="bg-gradient-to-r from-red-600 to-pink-600 rounded-2xl p-4 flex justify-between"><p className="text-sm font-bold">🔴 LIVE Sinta 123 penonton</p><button className="bg-white text-red-600 rounded-full px-3 py-1 text-xs font-bold">Live</button></div></div></div>)}
        {activeTab === 'dompet' && (<div className="p-4 space-y-4"><div className="bg-gradient-to-br from-violet-600 to-pink-600 rounded-[32px] p-6"><p className="text-white/70 text-sm">{t.saldo}</p><h2 className="text-3xl font-black">Rp {balance.toLocaleString('id-ID')}</h2><p className="text-sm mt-2">{t.coins}: {coins}</p><div className="grid grid-cols-3 gap-2 mt-4"><button onClick={handleTopup} className="bg-white text-violet-600 rounded-full py-2 text-xs font-black">{t.topup}</button><button className="bg-black/30 rounded-full py-2 text-xs">Convert</button><button className="bg-black/30 rounded-full py-2 text-xs">WD</button></div></div><div className="bg-[#1a1a1a] rounded-2xl p-4"><h3 className="font-bold mb-2">{t.riwayat}</h3>{transactions.map((tr, i) => <div key={i} className="flex justify-between text-sm py-2 border-b border-white/5"><div><p className="font-bold">{tr.type}</p><p className="text-xs text-white/40">{tr.time}</p></div><p>{tr.amount}</p></div>)}</div><div className="bg-[#1a1a1a] rounded-2xl p-4"><h3 className="font-bold mb-2">{t.kotakSaran}</h3><textarea value={saranText} onChange={e => setSaranText(e.target.value)} placeholder={t.tulisSaran} className="w-full bg-black border border-white/10 rounded-2xl p-3 text-sm h-20"></textarea><button onClick={() => { if (saranText) { setSaranList([{ text: saranText, reply: null }, ...saranList]); setSaranText(''); } }} className="w-full mt-2 bg-white text-black rounded-full py-2 font-bold text-sm">{t.kirimSaran}</button><div className="mt-3 space-y-2">{saranList.map((s, i) => <div key={i} className="bg-black p-2 rounded-xl text-sm"><p>{s.text}</p>{s.reply && <p className="text-green-400 text-xs">↳ {t.dibalas}: {s.reply}</p>}</div>)}</div></div></div>)}
        {activeTab === 'profil' && (<div className="p-4 space-y-4"><div className="bg-[#1a1a1a] rounded-[32px] p-6 text-center"><img src="https://i.pravatar.cc/150?img=12" className="w-20 h-20 rounded-full mx-auto mb-3" /><h2 className="font-black">{isOwner ? 'PEMILIK 👑' : form.name}</h2><p className="text-sm text-white/50">{isOwner ? 'pemilik / 1106' : form.email}</p></div>{isOwner && (<><div className="bg-[#1a1a1a] rounded-2xl p-4"><h3 className="font-bold mb-2">🔐 {t.dataTerenkripsi}</h3><div className="bg-black p-3 rounded-xl text-xs flex justify-between"><span>SeaBank 9015...1680</span><span className="text-green-400">● AES-256</span></div><div className="bg-black p-3 rounded-xl text-xs flex justify-between mt-2"><span>Midtrans Server Production</span><span className="text-green-400">● Secrets</span></div></div><div className="bg-[#1a1a1a] rounded-2xl p-4"><h3 className="font-bold mb-2">🎬 Upload Drakor Baru</h3><input placeholder="Judul Drakor" className="w-full bg-black border border-white/10 rounded-xl p-2 mb-2 text-sm" /><input placeholder="Link Video MP4" className="w-full bg-black border border-white/10 rounded-xl p-2 mb-2 text-sm" /><button className="w-full bg-violet-500 rounded-full py-2 text-sm font-bold">Upload ke Hiburan</button></div></>)}<div className="bg-[#1a1a1a] rounded-2xl p-4"><h3 className="font-bold mb-2">{t.bahasa}</h3><div className="grid grid-cols-3 gap-2">{Object.entries(LANGUAGES).map(([k, v]) => <button key={k} onClick={() => setLang(k)} className={`p-2 rounded-xl border text-sm ${lang === k ? 'bg-white text-black' : 'bg-black border-white/10'}`}>{v.flag}</button>)}</div></div><button onClick={() => setIsLoggedIn(false)} className="w-full bg-red-500/20 text-red-400 border border-red-500/20 rounded-full py-3 font-bold">{t.keluar}</button><p className="text-[10px] text-white/20 text-center mt-4">TOTAL: ~180 baris. Copy kabeh dari baris 1 import sampai } akhir. Paste di GitHub src/App.jsx via HP: Edit file > Select All > Paste > Commit</p></div>)}
      </div>
      {playingVideo && (<div className="fixed inset-0 z-50 bg-black/90 flex flex-col p-4"><div className="flex justify-between items-center mb-4"><h2 className="font-black text-sm">{t.playerTitle}: {playingVideo.title}</h2><button onClick={() => setPlayingVideo(null)} className="bg-white/10 w-10 h-10 rounded-full">✕</button></div><video src={playingVideo.video} controls autoPlay className="w-full rounded-2xl bg-black" poster={playingVideo.thumb}></video><div className="mt-4 bg-[#1a1a1a] rounded-2xl p-4"><h3 className="font-bold">{playingVideo.title}</h3><p className="text-sm text-white/60">{playingVideo.desc}</p><div className="flex gap-2 mt-3"><button className="flex-1 bg-white/10 rounded-full py-2 text-sm">❤️ Like</button><button className="flex-1 bg-gradient-to-r from-pink-500 to-violet-500 rounded-full py-2 text-sm font-bold">🎁 Gift</button></div></div></div>)}
      <div className="fixed bottom-0 left-1/2 -translate-x-1/2 w-full max-w-[480px] bg-[#1a1a1a]/90 backdrop-blur-xl border-t border-white/10 flex justify-around py-3">
        {[{ id: 'radar', icon: '📡' }, { id: 'chat', icon: '💬' }, { id: 'hiburan', icon: '🎬' }, { id: 'dompet', icon: '💰' }, { id: 'profil', icon: '👤' }].map(tab => (<button key={tab.id} onClick={() => setActiveTab(tab.id)} className={`flex flex-col items-center text-[10px] ${activeTab === tab.id ? 'text-white' : 'text-white/40'}`}><span className="text-xl">{tab.icon}</span><span>{getT(lang)[tab.id]}</span></button>))}
      </div>
    </div>
  );
}
